#!/usr/bin/env node
/**
 * Generate kapitan-sh alias registry from packages/commands/commands.json.
 */
import fs from 'node:fs';
import path from 'node:path';
import { DEFAULT_PATHS, resolvePath } from './lib/paths.mjs';
import {
  assertNoCdGitRegression,
  loadRegistry,
  posixDispatch,
  shellQuote,
} from './lib/registry.mjs';

function parseArgs(argv) {
  const options = {
    check: false,
    input: DEFAULT_PATHS.commandsJson,
    output: DEFAULT_PATHS.aliasesSh,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--check') options.check = true;
    else if (arg === '--input') options.input = resolvePath(argv[++i], options.input);
    else if (arg === '--output') options.output = resolvePath(argv[++i], options.output);
    else if (arg === '--help' || arg === '-h') {
      printHelp();
      process.exit(0);
    } else {
      console.error(`Unknown argument: ${arg}`);
      printHelp();
      process.exit(2);
    }
  }

  return options;
}

function printHelp() {
  console.log(`Usage: node packages/commands/scripts/generate-aliases.mjs [options]

Options:
  --input <path>   commands.json (default: packages/commands/commands.json)
  --output <path>  Shell output (default: packages/kapitan-sh/generated/aliases.sh)
  --check          Exit 1 if output differs from file on disk
  -h, --help       Show this help
`);
}

function renderAliases(registry) {
  const now = new Date().toISOString();
  const lines = [
    '#!/usr/bin/env bash',
    '# KAPiTaN OS — kapitan-sh alias registry',
    '# Generated by packages/commands/scripts/generate-aliases.mjs',
    '# Source: packages/commands/commands.json',
    `# Version: ${registry.version} | Commands: ${registry.commands.length}`,
    `# Generated at: ${now}`,
    '# DO NOT EDIT — regenerate with: node packages/commands/scripts/generate-aliases.mjs',
    '',
    'if [[ -n "${KAPITAN_ALIASES_LOADED:-}" ]]; then return 0 2>/dev/null || exit 0; fi',
    'KAPITAN_ALIASES_LOADED=1',
    '',
    'declare -gA KAPITAN_ALIAS_MAP=()',
    'declare -gA KAPITAN_ALIAS_ID=()',
    '',
  ];

  for (const command of registry.commands) {
    if (!command.posixArgv?.length) {
      lines.push(`# ${command.id} — AI/native stub (no POSIX alias)`);
      lines.push('');
      continue;
    }

    const dispatch = posixDispatch(command.posixArgv);
    const posixLabel = command.posix ?? command.posixArgv.join(' ');
    lines.push(`# ${command.id} | posix: ${posixLabel} | turkish: ${command.turkish} | short: ${command.short}`);

    if (command.replaces) {
      lines.push(`# replaces legacy alias: ${command.replaces}`);
    }

    lines.push(`KAPITAN_ALIAS_MAP[${shellQuote(command.turkish)}]=${shellQuote(dispatch)}`);
    lines.push(`KAPITAN_ALIAS_ID[${shellQuote(command.turkish)}]=${shellQuote(command.id)}`);
    lines.push(`KAPITAN_ALIAS_MAP[${shellQuote(command.short)}]=${shellQuote(dispatch)}`);
    lines.push(`KAPITAN_ALIAS_ID[${shellQuote(command.short)}]=${shellQuote(command.id)}`);

    if (command.posix && command.posix === command.posixArgv[0] && command.posixArgv.length === 1) {
      lines.push(`alias ${shellQuote(command.turkish)}=${shellQuote(dispatch)}`);
      if (command.short !== command.turkish) {
        lines.push(`alias ${shellQuote(command.short)}=${shellQuote(dispatch)}`);
      }
    }

    lines.push('');
  }

  lines.push('kapitan_registry_lookup() {');
  lines.push('  local token="$1"');
  lines.push('  printf "%s" "${KAPITAN_ALIAS_MAP[$token]:-}"');
  lines.push('}');
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function main() {
  const options = parseArgs(process.argv.slice(2));

  if (!fs.existsSync(options.input)) {
    console.error(`commands.json not found: ${options.input}`);
    process.exit(1);
  }

  const registry = loadRegistry(options.input);
  const regressionErrors = assertNoCdGitRegression(registry.commands);
  if (regressionErrors.length) {
    console.error('Registry regression checks failed:');
    for (const message of regressionErrors) console.error(`  - ${message}`);
    process.exit(1);
  }

  const content = renderAliases(registry);

  if (options.check) {
    if (!fs.existsSync(options.output)) {
      console.error(`Alias file missing (run generator first): ${options.output}`);
      process.exit(1);
    }
    const existing = fs.readFileSync(options.output, 'utf8');
    const normalize = (text) =>
      text.replace(/^# Generated at:.*$/m, '# Generated at: __TIMESTAMP__').trim();
    if (normalize(existing) !== normalize(content)) {
      console.error(`Out of sync: ${options.output}`);
      console.error('Run: node packages/commands/scripts/generate-aliases.mjs');
      process.exit(1);
    }
    console.log(`OK: ${path.relative(process.cwd(), options.output)} is up to date`);
    return;
  }

  fs.mkdirSync(path.dirname(options.output), { recursive: true });
  fs.writeFileSync(options.output, content, { mode: 0o755 });
  console.log(
    `Wrote ${path.relative(process.cwd(), options.output)} (${registry.commands.length} commands)`,
  );
}

main();